export const GET_CHANNEL_DETAILS_REQUEST = "GET_CHANNEL_DETAILS_REQUEST"
export const GET_CHANNEL_DETAILS_SUCCESS = "GET_CHANNEL_DETAILS_SUCCESS"
export const GET_CHANNEL_DETAILS_FAIL    = "GET_CHANNEL_DETAILS_FAIL"

export const UPDATE_CHANEL_REQUEST = "UPDATE_CHANEL_REQUEST"
export const UPDATE_CHANEL_SUCCESS = "UPDATE_CHANEL_SUCCESS"
export const UPDATE_CHANEL_FAIL    = "UPDATE_CHANEL_FAIL"

export const CHOOSE_MOVIE_REQUEST = "CHOOSE_MOVIE_REQUEST"
export const CHOOSE_MOVIE_SUCCESS = "CHOOSE_MOVIE_SUCCESS"
export const CHOOSE_MOVIE_FAIL    = "CHOOSE_MOVIE_FAIL"

export const REMOVE_MOVIE_REQUEST = "REMOVE_MOVIE_REQUEST"
export const REMOVE_MOVIE_SUCCESS = "REMOVE_MOVIE_SUCCESS"
export const REMOVE_MOVIE_FAIL    = "REMOVE_MOVIE_FAIL"