export const GET_CHANNEL_DETAILS_REQUEST = "GET_CHANNEL_DETAILS_REQUEST"
export const GET_CHANNEL_DETAILS_SUCCESS = "GET_CHANNEL_DETAILS_SUCCESS"
export const GET_CHANNEL_DETAILS_FAIL    = "GET_CHANNEL_DETAILS_FAIL"

export const UPDATE_CHANEL_REQUEST = "UPDATE_CHANEL_REQUEST"
export const UPDATE_CHANEL_SUCCESS = "UPDATE_CHANEL_SUCCESS"
export const UPDATE_CHANEL_FAIL    = "UPDATE_CHANEL_FAIL"

export const CHOOSE_MOVIE_REQUEST = "CHOOSE_MOVIE_REQUEST"
export const CHOOSE_MOVIE_SUCCESS = "CHOOSE_MOVIE_SUCCESS"
export const CHOOSE_MOVIE_FAIL    = "CHOOSE_MOVIE_FAIL"

export const REMOVE_MOVIE_REQUEST = "REMOVE_MOVIE_REQUEST"
export const REMOVE_MOVIE_SUCCESS = "REMOVE_MOVIE_SUCCESS"
export const REMOVE_MOVIE_FAIL    = "REMOVE_MOVIE_FAIL"

export const CREATE_CONTENT_REQUEST = "CREATE_CONTENT_REQUEST"
export const CREATE_CONTENT_SUCCESS = "CREATE_CONTENT_SUCCESS"
export const  CREATE_CONTENT_FAIL   = "CREATE_CONTENT_FAIL"

export const GET_ALL_CONTENT_REQUEST = "GET_ALL_CONTENT_REQUEST"
export const GET_ALL_CONTENT_SUCCESS = "GET_ALL_CONTENT_SUCCESS"
export const GET_ALL_CONTENT_FAIL    = "GET_ALL_CONTENT_FAIL"

export const LIKE_VIDEO_REQUEST = "LIKE_VIDEO_REQUEST"
export const LIKE_VIDEO_SUCCESS = "LIKE_VIDEO_SUCCESS"
export const LIKE_VIDEO_FAIL    = "LIKE_VIDEO_FAIL"

export const SINGLE_CONTENT_REQUEST = "SINGLE_CONTENT_REQUEST";
export const SINGLE_CONTENT_SUCCESS = "SINGLE_CONTENT_SUCCESS";
export const SINGLE_CONTENT_FAIL    = "SINGLE_CONTENT_FAIL";

export const ADD_COMMENT_REQUEST = "ADD_COMMENT_REQUEST"
export const ADD_COMMENT_SUCCESS = "ADD_COMMENT_SUCCESS"
export const ADD_COMMENT_FAIL    = "ADD_COMMENT_FAIL"

export const GET_POPULAR_REVIEWS_REQUEST = "GET_POPULAR_REVIEWS_REQUEST"
export const GET_POPULAR_REVIEWS_SUCCESS = "GET_POPULAR_REVIEWS_SUCCESS"
export const GET_POPULAR_REVIEWS_FAIL    = "GET_POPULAR_REVIEWS_FAIL"

export const GET_SUGGEST_REVIEWS_REQUEST = "GET_SUGGEST_REVIEWS_REQUEST"
export const GET_SUGGEST_REVEIWS_SUCCESS = "GET_SUGGEST_REVEIWS_SUCCESS"
export const GET_SUGGEST_REVIEWS_FAIL    = "GET_SUGGEST_REVIEWS_FAIL"

export const SUBCRIBE_REQUEST = "SUBCRIBE_REQUEST"
export const SUBCRIBE_SUCCESS = "SUBCRIBE_SUCCESS"
export const SUBCRIBE_FAIL    = "SUBCRIBE_FAIL"




export const LIKE_CONTENT_RESET = "LIKE_CONTENT_RESET"